---

- name: Install useful packages
  package: name="{{ item }}" state=present
  with_items:
    - curl
    - mosh
    - rsync
    - sshguard
    - tmux
    - man-db
    - mlocate

- name: Enable/start sshguard
  service: name=sshguard state=started enabled=yes

- name: Harden SSH
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config

- name: Restart sshd
  service:
    name: sshd
    state: restarted
    enabled: yes

...
